### PR TITLE
fix: declare variables which should not be managed by inline-snapshot

### PR DESCRIPTION
**Pull request by 15r10nk**
things which can be changed with the **next** inline-snapshot version to make clear who is responsible for the source code (inline-snapshot or the developer).

### CODE REVIEW

**Comment by alexmojaki** [comment]
I don't understand this. What's the difference between `Is(foo)` and `foo` when `foo` is a variable name?

**Comment by 15r10nk** [comment]
@alexmojaki, you are fast :smile:. 

I published this to show what I'm currently working on https://github.com/15r10nk/inline-snapshot/issues/123.

This makes only sense if you know that `Is(...)` will be a part of the next inline-snapshot version which allows the developer to take back control and to change code inside snapshots.

This makes it explicit who controls the source code and inline-snapshot will no longer try to change you code back with "update".

The value inside `Is(...)` can also change if the snapshot is evaluated multiple times and allow some constructs which are not possible today.

**Comment by samuelcolvin** [comment]
thanks, personally I think this looks good, but @alexmojaki and @Kludex mostly maintain this repo, so it's up to them.

**Comment by alexmojaki** [comment]
Closing because I think the underlying issue about long reports is resolved with the newest inline-snapshot and I don't think it's worth fixing merge conflicts here.

**Pull request closed without merging**
