### PR TITLE
Test Python 3.13 in CI

### PR DESCRIPTION
**Pull request by sydney-runkle**
Closes https://github.com/pydantic/logfire/issues/471

### CODE REVIEW

**Comment by alexmojaki** [comment]
Also add to `pyproject.toml`s. Maybe other files that I'm not thinking of.

**Comment by sydney-runkle** [comment]
Sure thing. Working off of https://github.com/pydantic/pydantic/pull/9743 somewhat.

**Comment by Kludex** [comment]
Depends on https://github.com/pydantic/logfire/pull/480

**Comment by sydney-runkle** [comment]
Going to close and reopen against `main` with a cleaner commit sequence.

**Pull request closed without merging**
