### PR TITLE
Keep the default span processor when `processors` is passed to `logfire.configure()`

### PR DESCRIPTION
**Pull request by alexmojaki**
Closes https://github.com/pydantic/logfire/issues/99

This is a breaking change, but since we'll probably do this eventually anyway it's best to do it now. I can't see a reason for the current behaviour.

### CODE REVIEW

**Comment by adriangb** [comment]
I assume if you want to get rid of the default processor you're supposed to pass `send_to_logfire=False`?

**Review by adriangb — APPROVED** [review]
OK, as long as that’s documented properly. Since you’re making a break I’d suggest changing the name of the parameter to `additional_span_processors` or similar.

**Comment by alexmojaki** [comment]
OK I've renamed, and `processors` will now raise an error telling you to use `additional_span_processors`.

**Review by adriangb — APPROVED** [review]

**Comment by adriangb** [comment]
Looks great!

**Pull request merged**
