### PR TITLE
Bump dependencies with `uv sync --upgrade`

### PR DESCRIPTION
**Pull request by sydney-runkle**
Should we automate doing this every week or so? I've added a CI workflow to do that, will probably have to test it out + do some debugging.

Summary:

```
 - aiohttp==3.10.9
 + aiohttp==3.10.10
 - anthropic==0.35.0
 + anthropic==0.36.1
 - charset-normalizer==3.3.2
 + charset-normalizer==3.4.0
 - cloudpickle==3.0.0
 + cloudpickle==3.1.0
 - distlib==0.3.8
 + distlib==0.3.9
 - fastapi==0.115.0
 + fastapi==0.115.2
 - griffe==1.3.2
 + griffe==1.4.0
 - huggingface-hub==0.25.1
 + huggingface-hub==0.25.2
 - jiter==0.5.0
 + jiter==0.6.1
 - mkdocs-material==9.5.39
 + mkdocs-material==9.5.41
 - mypy==1.11.2
 + mypy==1.12.0
 - openai==1.51.0
 + openai==1.51.2
 - psycopg2-binary==2.9.9
 + psycopg2-binary==2.9.10
 - pydantic==2.10.0a1 (from git+https://github.com/pydantic/pydantic@eda3eb472ce07e314858a7469e663f2e3c883578)
 + pydantic==2.10.0a1 (from git+https://github.com/pydantic/pydantic@7bb0e0affb8c16dd84580b443ea65f52c418273f)
 - pydantic-core==2.24.0
 + pydantic-core==2.24.2
 - pyright==1.1.383
 + pyright==1.1.385
 - setuptools==75.1.0
 + setuptools==75.2.0
 - sqlalchemy==2.0.35
 + sqlalchemy==2.0.36
 - starlette==0.38.6
 + starlette==0.40.0
 - testcontainers==4.8.1
 + testcontainers==4.8.2
 - tokenizers==0.20.0
 + tokenizers==0.20.1
 - uvicorn==0.31.0
 + uvicorn==0.32.0
 - vcrpy==6.0.1
 + vcrpy==6.0.2
 - yarl==1.13.1
 + yarl==1.15.2
```

### CODE REVIEW

**Comment by alexmojaki** [comment]
We already ignore the lockfile in CI for tests (but not linting) so when a dependency upgrade breaks things we have to manually upgrade the lockfile for the sake of local dev and then also fix some tests. Upgrading deps when nothing has meaningfully changed doesn't really achieve anything.

What would be useful is just running regular CI tests every day so that we find out about dependency problems sooner when there's no active SDK work.

**Comment by sydney-runkle** [comment]
Hmm, not sure I'm following - how would we know about dep issues if we didn't automatically upgrade? The act of opening a PR here would run linting / testing with the upgrades...

**Comment by alexmojaki** [comment]
Because we ignore the lockfile in tests in CI, so a PR (or daily CI if we add that) will suddenly fail, e.g. that's what happened with CI failures in https://github.com/pydantic/logfire/pull/414 (which got fixed in https://github.com/pydantic/logfire/pull/415).

**Comment by sydney-runkle** [comment]
Right, then we can push a fix to that PR proactively?

**Comment by alexmojaki** [comment]
If a PR gets opened automatically with upgraded deps and tests fail, we have to fix the tests ourselves, and checking out the automatic PR to fix it and allow merging isn't really easier than just running `uv sync --upgrade` locally on `main`.

Running CI daily would be good just for the sake of alerting about problems ASAP. Upgrading the lockfile daily would be a bit weird.

**Comment by sydney-runkle** [comment]
Makes sense, doesn't add much value.

**Comment by sydney-runkle** [comment]
Oops, meant to close this. I guess the jet lag is getting me. Here's the reversion: https://github.com/pydantic/logfire/pull/510

**Pull request merged**
