### PR TITLE
Check token in separate thread

### PR DESCRIPTION
**Pull request by alexmojaki**
Closes https://github.com/pydantic/logfire/issues/247

### CODE REVIEW

**Review by adriangb — APPROVED** [review]
Generally looks good to me. Seems like we never join the thread right? Do have a lock on configure()? What happens if I do;

configure()
while True:
  info()

?

**Comment by alexmojaki** [comment]
```python
from logfire import configure, info

configure(token='...')
info('hi')
```

```
14:01:46.559 hi
/Users/alex/work/logfire/logfire/_internal/config.py:849: UserWarning: Invalid Logfire token.
  warnings.warn('Invalid Logfire token.')
Failed to export batch code: 401, reason: {"detail":"Invalid token"}
/Users/alex/work/logfire/logfire/_internal/exporters/file.py:58: WritingFallbackWarning: Failed to export spans, writing to fallback file: /Users/alex/Library/Application Support/JetBrains/PyCharm2024.1/scratches/.logfire/logfire_spans.bin
  warnings.warn(
Failed to export batch code: 401, reason: {"detail":"Invalid token"}
```

**Comment by adriangb** [comment]
I mean what if it's a valid token. Does that `info()` call (1) warn if `configure()` hasn't actually finished, (2) wait for `configure()` to finish or (3) kick off another call to `configure()`?

**Comment by alexmojaki** [comment]
The code inside `check_token` does nothing critical, it just prints the dashboard URL if the token is valid or warns (previously errored) if not. We already have the token and can start using it immediately to export without checking it.

**Pull request merged**
