### PR TITLE
`sqlite3` instrumentation support added

### PR DESCRIPTION
**Pull request by deepakdinesh1123**
Please let me know if this is something that you guys would like to add to logfire, I will add some more tests and make any changes that you guys suggest.

TODO
- [ ] Add more tests

### CODE REVIEW

**Comment by alexmojaki** [comment]
Yes this would be appreciated. It'd also need docs.

**Comment by Kludex** [comment]
@deepakdinesh1123 Are you willing to resume your work on this PR?

**Comment by deepakdinesh1123** [comment]
@Kludex No, I am busy at work so I have not been able to work on this.

**Comment by Kludex** [comment]
@deepakdinesh1123 I'll close this PR since you don't have time to finish.

Let us know if you want to do it later. We'll be happy to help. :)

**Comment by Kludex** [comment]
We'll eventually implement this anyway.

**Comment by alexmojaki** [comment]
This is being done in https://github.com/pydantic/logfire/pull/634

**Pull request closed without merging**
